### ISSUE TITLE
pom.xml parent.relativePath lost when reading/writing using Maven

### ISSUE THREAD

**Issue by ia3andy** [fabric8-launcher/maven-model-helper#46] opened 2021-01-25 16:03 UTC
There may be other lost stuff, but I've got a reproducer for this one:
```java
///usr/bin/env jbang "$0" "$@" ; exit $?

//DEPS io.fabric8:maven-model-helper:17

import io.fabric8.maven.Maven;
import org.apache.maven.model.Model;

import java.nio.file.Path;

import static java.lang.System.*;

public class MavenHelperBugReprod {

    public static void main(String... args) {
        final Model model = Maven.readModel(Path.of("./pom.xml"));
        Maven.writeModel(model, Path.of("pom-mod.xml"));
    }
}

```

Run this script in a directory containing this pom.xml:
```xml

<?xml version="1.0" encoding="UTF-8"?>
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>org.acme</groupId>
    <artifactId>greeting-extension-parent</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <relativePath>../pom.xml</relativePath>
  </parent>
  <artifactId>greeting-extension-deployment</artifactId>
  <name>Greeting Extension - Deployment</name>
  <dependencies>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-arc-deployment</artifactId>
    </dependency>
    <dependency>
      <groupId>org.acme</groupId>
      <artifactId>greeting-extension</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-junit5-internal</artifactId>
      <scope>test</scope>
    </dependency>
  </dependencies>
  <build>
    <plugins>
      <plugin>
        <artifactId>maven-compiler-plugin</artifactId>
        <configuration>
          <annotationProcessorPaths>
            <path>
              <groupId>io.quarkus</groupId>
              <artifactId>quarkus-extension-processor</artifactId>
              <version>${quarkus.version}</version>
            </path>
          </annotationProcessorPaths>
        </configuration>
      </plugin>
    </plugins>
  </build>
</project>

```

Check the pom-mod.xml (it just lost the `parent.relativePath`)

**Comment by quintesse** [comment] 2021-01-25 16:12
How I love people using Jbang to reproduce bugs! :-D

**Comment by quintesse** [comment] 2021-01-25 16:14
Btw, I think you mean `relativePath`, right?

**Comment by ia3andy** [comment] 2021-01-25 16:16
Oops thanks @quintesse

**Comment by gastaldi** [comment] 2021-01-25 16:22
Having a look

**Comment by gastaldi** [comment] 2021-01-25 16:37
Turns out it's not a bug. The MavenXpp3Writer bundled with Maven 3.6.3 checks if the `relativePath` is different from the default value (`../pom.xml`) to decide if it should be written.

See the `parent` definition in https://maven.apache.org/ref/3.6.3/maven-model/maven.html 

Closing

**Closed by gastaldi** 2021-01-25 16:37 UTC

**Comment by ia3andy** [comment] 2021-01-25 17:20
Haha cool thanks @gastaldi :)
